### ISSUE TITLE
NoSuchMethodError crash report

### ISSUE THREAD

**Issue by kajsa** [nokia/PyVenvManage#10] opened 2019-09-26 17:12 UTC
Using PyVenvManage 1.2, with the following IntelliJ build - 

```
IntelliJ IDEA 2019.3 EAP (Ultimate Edition)
Build #IU-193.3793.14, built on September 25, 2019
IntelliJ IDEA EAP User
Expiration date: October 25, 2019
Runtime version: 11.0.4+10-b485.1 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14.6
GC: ParNew, ConcurrentMarkSweep
Memory: 1979M
Cores: 16
Registry: debugger.watches.in.variables=false
Non-Bundled Plugins: Groovy Console Plugin, Lombook Plugin, Pythonid, com.github.nokia.pyvenv, com.paperetto.dash, detekt, dk.demus.idea.CodeNarc, org.intellij.plugins.hcl, org.intellij.scala, org.jetbrains.plugins.vue
```

```
java.lang.NoSuchMethodError: 'java.lang.String com.jetbrains.python.sdk.PythonSdkType.getPythonExecutable(java.lang.String)'
	at com.github.nokia.VenvIconProvider.getLayerIcon(VenvIconProvider.java:40)
	at com.intellij.ui.CoreIconManager.createLayeredIcon(CoreIconManager.java:72)
	at com.intellij.ui.CoreIconManager.createLayeredIcon(CoreIconManager.java:19)
	at com.intellij.psi.impl.JavaDirectoryIconProvider.getIcon(JavaDirectoryIconProvider.java:65)
	at com.intellij.ide.projectView.impl.CompoundIconProvider.getIcon(CompoundIconProvider.java:34)
	at com.intellij.ide.projectView.impl.CompoundIconProvider.findIcon(CompoundIconProvider.java:60)
	at com.intellij.ide.scopeView.ScopeViewTreeModel$Node.getFolderIcon(ScopeViewTreeModel.java:496)
	at com.intellij.ide.scopeView.ScopeViewTreeModel$ProjectNode.lambda$createChildren$2(ScopeViewTreeModel.java:562)
	at com.intellij.util.SmartList.forEach(SmartList.java:348)
	at com.intellij.ide.scopeView.ScopeViewTreeModel$ProjectNode.createChildren(ScopeViewTreeModel.java:559)
	at com.intellij.ide.scopeView.ScopeViewTreeModel$FileNode.createChildren(ScopeViewTreeModel.java:697)
	at com.intellij.ide.scopeView.ScopeViewTreeModel$Node.getChildren(ScopeViewTreeModel.java:466)
	at com.intellij.ide.scopeView.ScopeViewTreeModel$GroupNode.createChildren(ScopeViewTreeModel.java:916)
	at com.intellij.ide.scopeView.ScopeViewTreeModel$Node.getChildren(ScopeViewTreeModel.java:466)
	at com.intellij.ide.scopeView.ScopeViewTreeModel.getChildCount(ScopeViewTreeModel.java:352)
	at com.intellij.ui.tree.BaseTreeModel.isLeaf(BaseTreeModel.java:12)
	at com.intellij.ide.scopeView.ScopeViewTreeModel.isLeaf(ScopeViewTreeModel.java:345)
	at com.intellij.ui.tree.AsyncTreeModel.getLeafState(AsyncTreeModel.java:443)
	at com.intellij.ui.tree.AsyncTreeModel.access$1800(AsyncTreeModel.java:42)
	at com.intellij.ui.tree.AsyncTreeModel$CmdGetChildren.load(AsyncTreeModel.java:614)
	at com.intellij.ui.tree.AsyncTreeModel$CmdGetChildren.getNode(AsyncTreeModel.java:587)
	at com.intellij.ui.tree.AsyncTreeModel$ObsolescentCommand.get(AsyncTreeModel.java:480)
	at com.intellij.ui.tree.AsyncTreeModel$ObsolescentCommand.get(AsyncTreeModel.java:446)
	at com.intellij.util.concurrency.Command$Processor.lambda$process$1(Command.java:48)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:986)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runInReadActionWithWriteActionPriority$0(ProgressIndicatorUtils.java:70)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runWithWriteActionPriority$1(ProgressIndicatorUtils.java:124)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:170)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:592)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:538)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:59)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:157)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runWithWriteActionPriority(ProgressIndicatorUtils.java:113)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:70)
	at com.intellij.util.concurrency.Invoker.invokeSafely(Invoker.java:171)
	at com.intellij.util.concurrency.Invoker.lambda$invokeLater$0(Invoker.java:106)
	at com.intellij.util.concurrency.Invoker$Background.lambda$offer$0(Invoker.java:448)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:222)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:30)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.execute(BoundedTaskExecutor.java:201)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:221)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:190)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by andrask** [comment] 2019-10-07 06:49
@kajsa than you for the bugreport.
One question: do you have the python plugin installed? https://plugins.jetbrains.com/plugin/7322-python-community-edition/ Unfortunately, it cannot be made mandatory as it would make the plugin specific to a given Jetbrains product.

**Comment by kajsa** [comment] 2019-10-08 18:20
Yes, I've currently got the Python plugin installed at version 2019.2.192.6817.14

**Comment by andrask** [comment] 2019-10-25 05:40
So I tried to set up your environment (the platform is a little newer snapshot but shouldn't be relevant to the issue). It seems like you are using an incompatible version of the python plugin. As you are running an EAP version of the platform you'll probably have to update to the EAP version of the plugin too:

```
07:18 $ ./gradlew runIde

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'PyVenvManage'.
> Plugin PythonCore:2019.2.192.6817.14 is not compatible to IC-193.4778.7

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

```
If I try with
pythonCoreVersion = "193.4778.7"
intelli.version 'IC-193.4778.7'
the plugin works as expected.

Sorry it took so long to check.

**Comment by andrask** [comment] 2019-10-31 05:39
@kajsa updating the python plugin may fix your issue. Can you please confirm?

**Comment by andrask** [comment] 2019-11-14 05:11
I'll close this bug now as the issue is probably solved but feel free to reopen if needed.

**Closed by andrask** 2019-11-14 05:11 UTC
